packaging_format = 2

id = "zusam"
name = "Zusam"
description.en = "A truly private space for you and your friends"
description.fr = "Un espace entièrement privé pour vous et vos amis"

version = "0.5.3~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = "Unlicense"
website = "https://zusam.org"
demo = "https://demo.zusam.org"
admindoc = "https://github.com/zusam/zusam/tree/master/documentation"
code = "https://some.forge.com/example/example"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = "no"
sso = "no"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zusam"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/zusam/zusam/archive/refs/tags/0.5.3.tar.gz"
        sha256 = "3d0add0993ac209f73be392a7735055f51b783cc7856285216f80c3e0e7db93d"

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "unzip ffmpeg php8.2 php8.2-fpm php8.2-xml php8.2-curl php8.2-mbstring php8.2-sqlite3 php-imagick php8.2-intl curl"
