packaging_format = 2

id = "zusam"
name = "Zusam"
description.en = "A truly private space for you and your friends"
description.fr = "Un espace entièrement privé pour vous et vos amis"

version = "0.5.3~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = "Unlicense"
website = "https://zusam.org"
demo = "https://demo.zusam.org"
admindoc = "https://github.com/zusam/zusam/tree/master/documentation"
code = "https://github.com/zusam/zusam"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    help.en = "Zusam can only be installed in a root domain or subdomain"
    help.fr = "Zusam ne peut être installé que dans un domaine racine ou un sous-domaine"
    type = "domain"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.first_user]
    ask.en = "Choose the Zusam's first user"
    ask.fr = "Choisissez le premier utilisateur de Zusam"
    type = "user"

    [install.first_user_pass]
    help.en = "This password is only used for the Zusam app"
    help.fr = "Ce mot de passe sera utilisé uniquement pour l'application Zusam"
    ask.en = "Enter a password for Zusam's first user"
    ask.fr = "Saisissez un mot de passe pour le premier utilisateur de Zusam"
    type = "password"

    [install.first_group]
    ask.en = "Enter the name of the first group of the first user"
    ask.fr = "Saississez le nom du  premier groupe du premier utilisateur"
    type = "string"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/zusam/zusam/archive/refs/tags/0.5.3.tar.gz"
        sha256 = "3d0add0993ac209f73be392a7735055f51b783cc7856285216f80c3e0e7db93d"

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"

    [resources.ports]

    [resources.apt]
    packages = "unzip ffmpeg php php-fpm php-xml php-curl php-mbstring php-sqlite3 php-imagick php-intl curl"
