#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=2048M

### This helper will compare the version of the currently installed app and the version of the upstream package.
### $upgrade_type can have 2 different values
### - UPGRADE_APP if the upstream app version has changed
### - UPGRADE_PACKAGE if only the YunoHost package has changed
### ynh_check_app_version_changed will stop the upgrade if the app is up to date.
### UPGRADE_APP should be used to upgrade the core app only if there's an upgrade to do.

#=================================================

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --full_replace
    if [ -f $install_dir/api/config/packages/sensio_framework_extra.yaml ]
    then
        ynh_safe_rm $install_dir/api/config/packages/sensio_framework_extra.yaml
    fi
fi

#=================================================
# ACTUAL UPDATE
#=================================================

ynh_script_progression "Proceeding to migration..."

pushd $install_dir
    ynh_script_progression "Proceeding to migration..."
    ynh_safe_rm $install_dir/api/var/cache/
    php$php_version api/bin/console doctrine:migration:migrate --no-interaction --allow-no-migration
    php$php_version api/bin/console zusam:migration

    ynh_script_progression "Pulling in external libraries with Composer..."
    ynh_composer_install
ynh_composer_exec install --no-dev  -c "2.4.2" -w $install_dir/api/
  cp -r app/dist/* public/
popd

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# This should be a literal copypasta of what happened in the install's "System configuration" section

ynh_config_add_phpfpm

ynh_config_add_nginx

# ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
