#!/bin/bash

source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=2048M

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="data"

if [ -f $install_dir/api/config/packages/sensio_framework_extra.yaml ]; then
      ynh_safe_rm $install_dir/api/config/packages/sensio_framework_extra.yaml
fi


#=================================================
# ACTUAL UPDATE
#=================================================

pushd $install_dir
    ynh_script_progression "Proceeding to migration..."
    ynh_safe_rm $install_dir/api/var/cache/
    ls -lah $install_dir
    ynh_hide_warnings php$php_version $install_dir/api/bin/console doctrine:migration:migrate --no-interaction --allow-no-migration
    ynh_hide_warnings php$php_version $install_dir/api/bin/console zusam:migration

    ynh_script_progression "Pulling in external libraries with Composer..."
    ynh_composer_exec install --no-dev -d $install_dir/api
    
    cp -r app/dist/* public/
    chown -R $app:www-data "$install_dir/public"
    chown -R $app:www-data "$install_dir/api"
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

# ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
